import { KategoriMasjid } from "@/lib/validation";

export const initialForm = {
  // Info Umum
  nama: "",
  alamat: "",
  latitude: "",
  longitude: "",
  idProvinsi: "",
  idKota: "",
  idKecamatan: "",
  idDesa: "",
  tahunDibangun: "",
  budgetAwal: "",
  // Fisik & Bangunan
  luasSekarang: "",
  kapasitas: "",
  materialUtama: "",
  statusPerluasan: "",
  riwayatRenovasi: "",
  targetPerluasan: "",
  // Legalitas & Kondisi
  statusTanah: "",
  statusListrik: "",
  // kondisi: "RUSAK_SEDANG",
  kategori: "Pelosok_Pedalaman" as KategoriMasjid,
  waktuKerusakan: "",
  alasan: "",
  dampakKerusakan: "",
  hambatanAktivitas: "",
  kondisiHujan: "",
  riwayatRoboh: "",
  usahaPerbaikan: "",
  riwayatMenerimaBantuan: "",
  // Data Masyarakat
  kkMuslim: "",
  jumlahJamaah: "",
  avgProfesiJamaah: "",
  avgGajiJamaah: "",
  usahaJamaah: "",
  // Akses & Lingkungan
  jarakKeKota: "",
  waktuTempuhKeKota: "",
  kondisiAksesKota: "",
  kondisiAksesDesa: "",
  jenisKendaraan: "",
  hambatanAkses: "",
  gantiNama: "",
  masjidTerdekat: "",
  // Aktivitas Ibadah
  kelayakan: "",
  aktivitasMasjid: "",
  jamaahSubuh: "",
  jumlahSantri: "",
  // PIC & Catatan
  namaPic: "",
  jabatanPic: "",
  kontakPic: "",
  catatan: "",
};